---

- name: Converge
  hosts: all
  pre_tasks:
    - name: update apt repository
      when: 'ansible_pkg_mgr == "apt"'
      apt:
        update_cache: true
  roles:
    - role: ansible-role-beats
      vars:
        elk_beats:
          filebeat:
            configuration:
              filebeat.inputs:
                - type: log
                  enabled: false
                  paths:
                    - /var/log/*.log
              filebeat.config.modules:
                path: ${path.config}/modules.d/*.yml
                reload.enabled: false
              setup.template.settings:
                index.number_of_shards: 1
              setup.kibana:
              output.elasticsearch:
                hosts: ["localhost:9200"]
              processors:
                - add_host_metadata: ~
                - add_cloud_metadata: ~
